-- 20260319_initial_schema.sql

-- 1. Profiles Table (Extends Supabase auth.users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    date_of_birth DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for privacy
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. IPSS_Assessments Table
CREATE TABLE public.ipss_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    q1_incomplete_emptying INT CHECK (q1_incomplete_emptying BETWEEN 0 AND 5),
    q2_frequency INT CHECK (q2_frequency BETWEEN 0 AND 5),
    q3_intermittency INT CHECK (q3_intermittency BETWEEN 0 AND 5),
    q4_urgency INT CHECK (q4_urgency BETWEEN 0 AND 5),
    q5_weak_stream INT CHECK (q5_weak_stream BETWEEN 0 AND 5),
    q6_straining INT CHECK (q6_straining BETWEEN 0 AND 5),
    q7_nocturia INT CHECK (q7_nocturia BETWEEN 0 AND 5),
    q8_quality_of_life INT CHECK (q8_quality_of_life BETWEEN 0 AND 6),
    total_score INT NOT NULL,
    severity TEXT NOT NULL, -- 'Mild', 'Moderate', 'Severe'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ipss_assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own assessments" ON public.ipss_assessments FOR SELECT USING (auth.uid() = user_id);

-- 3. Treatment_Recommendations Table
CREATE TABLE public.treatment_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id UUID UNIQUE NOT NULL REFERENCES public.ipss_assessments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    medical_disclaimer TEXT NOT NULL,
    clinical_consultation_required BOOLEAN NOT NULL DEFAULT FALSE,
    recommended_pathways JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.treatment_recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own recommendations" ON public.treatment_recommendations FOR SELECT USING (auth.uid() = user_id);

-- 4. Chat_Logs Table
CREATE TABLE public.chat_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    processed BOOLEAN DEFAULT FALSE -- Flag for the AI FAQ scanner
);

ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own chat logs" ON public.chat_logs FOR SELECT USING (auth.uid() = user_id);

-- 5. FAQ_AutoGenerated Table (Public Read)
CREATE TABLE public.faq_autogenerated (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question TEXT UNIQUE NOT NULL,
    answer TEXT NOT NULL,
    keyword_triggers TEXT[],
    mention_frequency INT DEFAULT 1,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.faq_autogenerated ENABLE ROW LEVEL SECURITY;
-- FAQs are public to all users
CREATE POLICY "Anyone can view FAQs" ON public.faq_autogenerated FOR SELECT USING (true);
