-- 20260404010000_master_reset.sql
-- COMPLETE MIST-AI DATABASE WIPE & REBUILD (TESTING ENVIRONMENT)

-- 1. NUKE EXISTING TABLES
DROP TABLE IF EXISTS public.access_requests CASCADE;
DROP TABLE IF EXISTS public.chat_logs CASCADE;
DROP TABLE IF EXISTS public.treatment_recommendations CASCADE;
DROP TABLE IF EXISTS public.ipss_assessments CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.knowledge_base CASCADE;
DROP TABLE IF EXISTS public.faq_autogenerated CASCADE;

-- 2. REBUILD KNOWLEDGE BASE (Vector DB)
CREATE TABLE public.knowledge_base (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding VECTOR(768)
);

CREATE TABLE public.faq_autogenerated (
    id SERIAL PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- 3. REBUILD PROFILES TABLE (Now includes email, age, height, weight)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT CHECK (role IN ('patient', 'doctor', 'admin')) DEFAULT 'patient',
  first_name TEXT,
  last_name TEXT,
  email TEXT, -- Email made publically visible here for testing/search
  age INT,
  height_cm DECIMAL,
  weight_kg DECIMAL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. REBUILD CLINICAL ASSESSMENTS
CREATE TABLE public.ipss_assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  q1_incomplete_emptying INT CHECK (q1_incomplete_emptying BETWEEN 0 AND 5),
  q2_frequency INT CHECK (q2_frequency BETWEEN 0 AND 5),
  q3_intermittency INT CHECK (q3_intermittency BETWEEN 0 AND 5),
  q4_urgency INT CHECK (q4_urgency BETWEEN 0 AND 5),
  q5_weak_stream INT CHECK (q5_weak_stream BETWEEN 0 AND 5),
  q6_straining INT CHECK (q6_straining BETWEEN 0 AND 5),
  q7_nocturia INT CHECK (q7_nocturia BETWEEN 0 AND 5),
  q8_quality_of_life INT CHECK (q8_quality_of_life BETWEEN 0 AND 6),
  total_score INT NOT NULL,
  severity TEXT CHECK (severity IN ('Mild', 'Moderate', 'Severe')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. REBUILD TREATMENT RECOMMENDATIONS
CREATE TABLE public.treatment_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  assessment_id UUID REFERENCES public.ipss_assessments(id) ON DELETE CASCADE,
  recommended_plan TEXT NOT NULL,
  ai_rationale TEXT,
  doctor_override TEXT,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. REBUILD AI CHAT LOGS
CREATE TABLE public.chat_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  query TEXT NOT NULL,
  ai_response TEXT NOT NULL,
  context_used TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. REBUILD ACCESS REQUESTS MANAGER
CREATE TABLE public.access_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  patient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(doctor_id, patient_id)
);

-- 8. RLS SECURITY POLICIES (Required for Frontend React to function properly)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipss_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faq_autogenerated ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles read" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Profiles update" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Profiles insert" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Patient IPSS Isolation" ON public.ipss_assessments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Patient IPSS Insert" ON public.ipss_assessments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Global Doctor IPSS Analytics" ON public.ipss_assessments FOR SELECT USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('doctor', 'admin'));

CREATE POLICY "Users can view own chat logs" ON public.chat_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own chat logs" ON public.chat_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users view own requests" ON public.access_requests FOR SELECT USING (auth.uid() = doctor_id OR auth.uid() = patient_id);
CREATE POLICY "Docs insert requests" ON public.access_requests FOR INSERT WITH CHECK (auth.uid() = doctor_id);
CREATE POLICY "Patients update requests" ON public.access_requests FOR UPDATE USING (auth.uid() = patient_id);
