-- ==============================================================
-- 🚨 DANGER: FULL DATABASE RESET & REMAKE
-- ==============================================================
-- This script permanently DROPS all your existing customized tables
-- and completely builds out the new, perfected MIST-AI Schema.
-- It also injects a pristine Doctor and Patient account with dummy data!

-- --------------------------------------------------------------
-- 1. NUKE THE TABLES (Cascade automatically drops policies/fkeys)
-- --------------------------------------------------------------
DROP TABLE IF EXISTS public.knowledge_base CASCADE;
DROP TABLE IF EXISTS public.faq_autogenerated CASCADE;
DROP TABLE IF EXISTS public.chat_logs CASCADE;
DROP TABLE IF EXISTS public.treatment_recommendations CASCADE;
DROP TABLE IF EXISTS public.ipss_assessments CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Also delete our specific mock users from the auth table
DELETE FROM auth.users WHERE email IN ('doctor@mist.com', 'patient@mist.com');

-- --------------------------------------------------------------
-- 2. CREATE THE PERFECTED SCHEMA
-- --------------------------------------------------------------

-- Allow the Vector plugin
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2.1 Profiles Table (Fixed constraints for easy app upserting)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    date_of_birth DATE,
    role TEXT DEFAULT 'patient', -- Allows 'patient', 'doctor', 'admin' RBAC
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Profiles read" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Profiles update" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Profiles insert" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- 2.2 IPSS_Assessments
CREATE TABLE public.ipss_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    q1_incomplete_emptying INT,
    q2_frequency INT,
    q3_intermittency INT,
    q4_urgency INT,
    q5_weak_stream INT,
    q6_straining INT,
    q7_nocturia INT,
    q8_quality_of_life INT,
    total_score INT NOT NULL,
    severity TEXT NOT NULL, 
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.ipss_assessments ENABLE ROW LEVEL SECURITY;
-- Patients see their own; Doctors/Admins see everyone's
CREATE POLICY "Patient IPSS Isolation" ON public.ipss_assessments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Patient IPSS Insert" ON public.ipss_assessments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Global Doctor IPSS Analytics" ON public.ipss_assessments FOR SELECT USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('doctor', 'admin'));

-- 2.3 Treatment_Recommendations
CREATE TABLE public.treatment_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id UUID UNIQUE NOT NULL REFERENCES public.ipss_assessments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    medical_disclaimer TEXT NOT NULL,
    clinical_consultation_required BOOLEAN NOT NULL DEFAULT FALSE,
    recommended_pathways JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.treatment_recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Patient Recs Isolation" ON public.treatment_recommendations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Patient Recs Insert" ON public.treatment_recommendations FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Global Doctor Recs Analytics" ON public.treatment_recommendations FOR SELECT USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('doctor', 'admin'));

-- 2.4 Chat Logs (for dynamic RAG analysis)
CREATE TABLE public.chat_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    processed BOOLEAN DEFAULT FALSE
);
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own chat logs" ON public.chat_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own chat logs" ON public.chat_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 2.5 FAQ Engine
CREATE TABLE public.faq_autogenerated (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question TEXT UNIQUE NOT NULL,
    answer TEXT NOT NULL,
    keyword_triggers TEXT[],
    mention_frequency INT DEFAULT 1,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.faq_autogenerated ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view FAQs" ON public.faq_autogenerated FOR SELECT USING (true);


-- 2.6 Vector Knowledge Base
CREATE TABLE public.knowledge_base (
  id BIGSERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  url TEXT,
  embedding VECTOR(768)
);
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read knowledge base" ON public.knowledge_base FOR SELECT USING (true);


-- --------------------------------------------------------------
-- 3. INJECT PERFECT MOCKS
-- --------------------------------------------------------------
DO $$
DECLARE
  patient_id UUID := gen_random_uuid();
  doctor_id UUID := gen_random_uuid();
  mock_assessment_id UUID := gen_random_uuid();
BEGIN
  -- 1) MOCK PATIENT
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at) 
  VALUES (patient_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'patient@mist.com', crypt('patientpassword', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Patient Demo"}', now(), now()) ON CONFLICT DO NOTHING;
  
  INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at)
  VALUES (patient_id, patient_id, patient_id::text, format('{"sub":"%s","email":"%s"}', patient_id::text, 'patient@mist.com')::jsonb, 'email', now(), now()) ON CONFLICT DO NOTHING;
  
  INSERT INTO public.profiles (id, first_name, last_name, role) VALUES (patient_id, 'Generic', 'Patient', 'patient')
  ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;
  
  -- Create a sample severe BPH submission for the new Patient
  INSERT INTO public.ipss_assessments (id, user_id, q1_incomplete_emptying, q2_frequency, q3_intermittency, q4_urgency, q5_weak_stream, q6_straining, q7_nocturia, q8_quality_of_life, total_score, severity)
  VALUES (mock_assessment_id, patient_id, 4, 3, 5, 4, 5, 2, 4, 5, 27, 'Severe');
  
  INSERT INTO public.treatment_recommendations (user_id, assessment_id, medical_disclaimer, clinical_consultation_required, recommended_pathways)
  VALUES (patient_id, mock_assessment_id, 'This is a mock clinical recommendation.', true, '["UroLift System (PUL)", "Rezum Water Vapor Therapy", "TURP"]'::jsonb);


  -- 2) MOCK DOCTOR
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at) 
  VALUES (doctor_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'doctor@mist.com', crypt('doctorpassword', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Doctor Demo"}', now(), now()) ON CONFLICT DO NOTHING;

  INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at)
  VALUES (doctor_id, doctor_id, doctor_id::text, format('{"sub":"%s","email":"%s"}', doctor_id::text, 'doctor@mist.com')::jsonb, 'email', now(), now()) ON CONFLICT DO NOTHING;
  
  INSERT INTO public.profiles (id, first_name, last_name, role) VALUES (doctor_id, 'Dr. Smith', 'Urologist', 'admin')
  ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;

END $$;
