import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import 'https://deno.land/x/xhr@0.3.0/mod.ts' // Required for OpenAI Edge environment
import OpenAI from 'npm:openai@4'

serve(async (req: Request) => {
  try {
    const authHeader = req.headers.get('Authorization')
    if (authHeader !== `Bearer ${Deno.env.get('CRON_SECRET')}`) {
      return new Response('Unauthorized Access', { status: 401 })
    }

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )
    
    const openai = new OpenAI({ apiKey: Deno.env.get('OPENAI_API_KEY') })

    const { data: recentLogs, error: logError } = await supabaseAdmin
      .from('chat_logs')
      .select('id, content')
      .eq('role', 'user')
      .eq('processed', false)

    if (logError || !recentLogs || recentLogs.length === 0) {
      return new Response('No novel log insights required', { status: 200 })
    }

    const userQueries = recentLogs.map(log => log.content)
    const logIds = recentLogs.map(log => log.id)

    const systemPrompt = `
      You are a specialized urology AI analyst. Review these unprocessed patient queries regarding BPH and Minimally Invasive Surgical Therapies (MIST).
      Extract up to 3 high-frequency novel questions (avoid generic questions like "What is BPH?").
      Return strict JSON matching this structure:
      { "faqs": [{ "question": "...", "answer": "...", "keywords": ["..."], "frequency_estimate": 1 }] }
      You MUST append a medical disclaimer to every answer block.
    `;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: JSON.stringify(userQueries) }
      ],
      response_format: { type: "json_object" } // Using Object encapsulation
    });

    const parsedData = JSON.parse(response.choices[0].message.content || "{}");
    const faqs = parsedData.faqs || [];

    for (const faq of faqs) {
      const { data: existing } = await supabaseAdmin
        .from('faq_autogenerated')
        .select('id, mention_frequency')
        .ilike('question', faq.question)
        .single()

      if (existing) {
        await supabaseAdmin
          .from('faq_autogenerated')
          .update({ 
            mention_frequency: existing.mention_frequency + faq.frequency_estimate,
            last_updated: new Date().toISOString()
          })
          .eq('id', existing.id)
      } else {
        await supabaseAdmin
          .from('faq_autogenerated')
          .insert({
            question: faq.question,
            answer: faq.answer,
            keyword_triggers: faq.keywords,
            mention_frequency: faq.frequency_estimate
          })
      }
    }

    await supabaseAdmin
      .from('chat_logs')
      .update({ processed: true })
      .in('id', logIds)

    return new Response('FAQ Update Pipeline Execution Successful', { status: 200 })

  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "An unknown error occurred"
    return new Response(JSON.stringify({ error: message }), { status: 500 })
  }
})
